elf: fix cgo include paths
On some systems the cgo processing fails with missing headers:

lib/nlattr.c:10:10: fatal error: include/nlattr.h: No such file or directory
10 | #include "include/nlattr.h"
   |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

This commit adds the header path to cgo CFLAGS that then gets passed
to gcc.