Fix compilation error in 32-architectures
It caused error `bpffs/fs.go:20: constant 3405662737 overflows int32`, see https://circleci.com/gh/weaveworks/scope/7239