bcc: cast reader explicitly
Newer versions of go (1.8+) are more strict about this, so the
compilation failed:

```
github.com/iovisor/gobpf/bcc
bcc/perf.go:131: cannot use reader (type unsafe.Pointer) as type *C.struct_perf_reader in argument to func literal
```

Cast it explicitly.